version: '3.7'

networks:
  app-network:
    driver: bridge

volumes:
  data-volume:
    driver: local

services:
  openldap:
    build:
      context: ./openldap
      dockerfile: Dockerfile
    image: open-ldap-admin/openldap:local
    volumes:
      - ./openldap/:/app
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ADMIN_PASSWORD=$LDAP_ADMIN_PASSWORD
    restart: unless-stopped
    networks:
      - app-network
